---
- hosts: all
  gather_facts: true
  tasks:
    - name: Check for held packages
      shell: sudo apt-mark showhold
      register: held_packages
      changed_when: false

    - name: Unhold any held packages
      shell: sudo apt-mark unhold {{ item }}
      loop: "{{ held_packages.stdout_lines }}"
      when: held_packages.stdout_lines|length > 0
      changed_when: true

    - name: Clean package cache
      command: |
        sudo apt-get clean
        sudo apt-get update
      changed_when: true

    - name: Include the mongodb role
      include_role:
        name: mongodb
