---
- hosts: all
  become: yes
  become_method: sudo
  become_user: root

  vars:
    db_version: "{{ morpheus['customOptions']['dbaasVersion'] }}"
    db_name: "{{ morpheus['customOptions']['dbName'] }}"
    db_user: "{{ morpheus['customOptions']['dbaasUsername'] }}"
    db_password: "{{ morpheus['customOptions']['dbaasPassword'] }}"
 
  tasks:
   - name: Install required packages
     apt:
       name:
         - sudo
         - acl
         - python3-pip
         - python3-mysqldb
       state: present
       update_cache: yes

   - name: Install MySQL Server
     apt:
       pkg:
         - mysql-server
         - mysql-client
       state: present
       update_cache: yes

   - name: Ensure MySQL is running
     systemd:
       name: mysql
       state: started
       enabled: yes

   - name: Create application database
     mysql_db:
       name: "{{ db_name }}"
       state: present
       login_unix_socket: /var/run/mysqld/mysqld.sock

   - name: Create database user
     mysql_user:
       name: "{{ db_user }}"
       password: "{{ db_password }}"
       priv: "{{ db_name }}.*:ALL"
       host: '%'
       state: present
       login_unix_socket: /var/run/mysqld/mysqld.sock

   - name: Allow remote connections
     replace:
       path: /etc/mysql/mysql.conf.d/mysqld.cnf
       regexp: '^bind-address\s*=\s*127\.0\.0\.1'
       replace: 'bind-address = 0.0.0.0'
     notify: Restart MySQL

  handlers:
   - name: Restart MySQL
     systemd:
       name: mysql
       state: restarted
