---
- hosts: all
  become: yes
  become_method: sudo
  become_user: root
 
  vars:
    # Default superuser values if no custom inputs
    default_username: "root"
    default_password: "root"
    default_dbname: "mysql"
    
    # Use custom inputs if defined, otherwise use defaults
    dbaas_username: "{{ morpheus['customOptions']['dbaasUsername'] | default(default_username) }}"
    dbaas_password: "{{ morpheus['customOptions']['dbaasPassword'] | default(default_password) }}"
    db_name: "{{ morpheus['customOptions']['dbName'] | default(default_dbname) }}"
 
  tasks:
   - name: Install required packages
     apt:
       name:
         - sudo
         - acl
         - python3-pip
         - python3-mysqldb
       state: present
       update_cache: yes
 
   - name: Install MySQL Server
     apt:
       pkg:
         - mysql-server
         - mysql-client
       state: present
       update_cache: yes
 
   - name: Ensure MySQL is running
     systemd:
       name: mysql
       state: started
       enabled: yes
 
   - name: Create application database
     mysql_db:
       name: "{{ db_name }}"
       state: present
       login_unix_socket: /var/run/mysqld/mysqld.sock
 
   - name: Create database user
     mysql_user:
       name: "{{ dbaas_username }}"
       password: "{{ dbaas_password }}"
       priv: "{{ '*.*:ALL,GRANT' if dbaas_username == 'root' else db_name + '.*:ALL' }}"
       host: '%'
       state: present
       login_unix_socket: /var/run/mysqld/mysqld.sock
 
   - name: Allow remote connections
     replace:
       path: /etc/mysql/mysql.conf.d/mysqld.cnf
       regexp: '^bind-address\s*=\s*127\.0\.0\.1'
       replace: 'bind-address = 0.0.0.0'
     notify: Restart MySQL
 
  handlers:
   - name: Restart MySQL
     systemd:
       name: mysql
       state: restarted
