---
- hosts: all
  become: yes
  become_method: sudo
  become_user: root

  tasks:
   - name: Install required packages
     apt:
       name:
         - sudo
         - acl
         - python3-pip
         - python3-mysqldb
       state: present
       update_cache: yes

   - name: Install MySQL Server
     apt:
       pkg:
         - mysql-server
         - mysql-client
       state: present
       update_cache: yes

   - name: Ensure MySQL is running
     systemd:
       name: mysql
       state: started
       enabled: yes

   - name: Create application database
     mysql_db:
       name: "demodb"
       state: present
       login_unix_socket: /var/run/mysqld/mysqld.sock

   - name: Create database user
     mysql_user:
       name: "demouser"
       password: "demopassword123"
       priv: "demodb.*:ALL"
       host: '%'
       state: present
       login_unix_socket: /var/run/mysqld/mysqld.sock

   - name: Allow remote connections
     replace:
       path: /etc/mysql/mysql.conf.d/mysqld.cnf
       regexp: '^bind-address\s*=\s*127\.0\.0\.1'
       replace: 'bind-address = 0.0.0.0'
     notify: Restart MySQL

  handlers:
   - name: Restart MySQL
     systemd:
       name: mysql
       state: restarted
