- hosts: all
  vars:
    ansible_ssh_pipelining: no
  become: yes
  become_method: sudo
  become_user: root
  
  tasks:
    - name: Install PostgreSQL packages
      apt:
        pkg:
          - postgresql-12
          - postgresql-contrib-12
          - python3-pip
          - acl
        state: present
        update_cache: yes

    - name: Create PostgreSQL tasks
      block:
        - name: Create application database
          become_user: postgres
          postgresql_db:
            name: demodb
            state: present

        - name: Create database user
          become_user: postgres
          postgresql_user:
            name: demouser
            password: demodb
            state: present

        - name: Grant database privileges
          become_user: postgres
          postgresql_privs:
            type: database
            database: demodb
            roles: demouser
            privs: ALL

        - name: Configure PostgreSQL authentication
          become_user: postgres
          postgresql_pg_hba:
            dest: "/etc/postgresql/12/main/pg_hba.conf"
            contype: host
            databases: all
            users: demouser
            address: 0.0.0.0/0
            method: md5
            create: true
