---
- hosts: all
  become: yes
  become_method: sudo
  become_user: root
 
  tasks:
   - name: Install required packages
     apt:
       name:
         - sudo
         - acl
         - lsb-release
         - ca-certificates
         - curl
       state: present
       update_cache: yes

   - name: Create keyrings directory
     file:
       path: /etc/apt/keyrings
       state: directory
       mode: '0755'

   - name: Add PostgreSQL signing key
     shell: |
       curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /etc/apt/keyrings/postgresql.gpg
     args:
       creates: /etc/apt/keyrings/postgresql.gpg

   - name: Add PostgreSQL repository
     apt_repository:
       repo: "deb [signed-by=/etc/apt/keyrings/postgresql.gpg] http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
       state: present
       filename: postgresql
       update_cache: yes

   - name: Install PostgreSQL packages
     apt:
       pkg:
         - postgresql-15
         - postgresql-contrib-15
         - python3-pip
       state: present
       update_cache: yes

   - name: Install Python PostgreSQL dependencies
     pip:
       name: psycopg2-binary
       state: present

   - name: Ensure PostgreSQL service running
     systemd:
       name: postgresql
       state: started
       enabled: yes

   - name: Create application database
     become_user: postgres
     postgresql_db:
       name: demodb
       state: present

   - name: Create database user
     become_user: postgres
     postgresql_user:
       name: demouser
       password: demodb
       state: present

   - name: Grant database privileges
     become_user: postgres
     postgresql_privs:
       type: database
       database: demodb
       roles: demouser
       privs: ALL

   - name: Configure PostgreSQL authentication
     become_user: postgres
     postgresql_pg_hba:
       dest: "/etc/postgresql/15/main/pg_hba.conf"
       contype: host
       databases: all
       users: demouser
       address: 0.0.0.0/0
       method: md5
       create: true
     notify: Restart PostgreSQL

  handlers:
   - name: Restart PostgreSQL
     systemd:
       name: postgresql
       state: restarted
