---
- hosts: all
  become: yes
  become_method: sudo
  become_user: root
  
  pre_tasks:
    - name: Ensure required system packages are installed
      apt:
        pkg:
          - postgresql-12
          - postgresql-contrib-12
          - python3-pip
        state: present
        update_cache: yes

    - name: Install Python PostgreSQL dependencies
      pip:
        name: 
          - psycopg2-binary
        state: present

  tasks:
    - name: Ensure PostgreSQL service is running
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Configure PostgreSQL listen addresses
      lineinfile:
        path: "/etc/postgresql/12/main/postgresql.conf"
        regexp: "^#?listen_addresses.+$"
        line: "listen_addresses = '{{ ansible_default_ipv4.address }}, localhost'"
        mode: 0644

    - name: Create application database
      become: yes
      become_user: postgres
      postgresql_db:
        name: demodb
        state: present

    - name: Create database user
      become: yes
      become_user: postgres
      postgresql_user:
        name: demouser
        password: demodb
        state: present

    - name: Grant database privileges
      become: yes
      become_user: postgres
      postgresql_privs:
        type: database
        database: demodb
        roles: demouser
        privs: ALL

    - name: Configure PostgreSQL authentication
      become: yes
      become_user: postgres
      postgresql_pg_hba:
        dest: "/etc/postgresql/12/main/pg_hba.conf"
        contype: host
        databases: all
        users: demouser
        address: 0.0.0.0/0
        method: md5
        create: true

  handlers:
    - name: Restart PostgreSQL
      systemd:
        name: postgresql
        state: restarted
