---
- hosts: all
  become: yes
  become_method: sudo
  become_user: root
  
  vars:
    # Use the root password for SA
    sa_password: "{{ morpheus['customOptions']['dbRootPassword'] }}"
 
  tasks:
    - name: Install prerequisites
      apt:
        name:
          - curl
          - gnupg2
          - apt-transport-https
          - wget
          - software-properties-common
        state: present
        update_cache: yes
    
    # Import Microsoft's GPG key
    - name: Import Microsoft GPG key
      shell: |
        curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft-prod.gpg
        chmod 644 /usr/share/keyrings/microsoft-prod.gpg
      args:
        creates: /usr/share/keyrings/microsoft-prod.gpg
    
    # Add SQL Server 2019 repository for Ubuntu 22.04
    # Note: Since 2019 doesn't have an official 22.04 repo, we use the 18.04 repo
    - name: Add SQL Server 2019 repository
      apt_repository:
        repo: deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-prod.gpg] https://packages.microsoft.com/ubuntu/18.04/mssql-server-2019 bionic main
        state: present
        filename: mssql-server
        update_cache: yes
    
    # Add the tools repository for Ubuntu 22.04
    - name: Add Microsoft tools repository
      apt_repository:
        repo: deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-prod.gpg] https://packages.microsoft.com/ubuntu/22.04/prod jammy main
        state: present
        filename: msprod
        update_cache: yes
    
    # Install SQL Server 2019
    - name: Install SQL Server 2019
      shell: |
        ACCEPT_EULA=Y MSSQL_SA_PASSWORD="{{ sa_password }}" apt-get install -y --allow-downgrades mssql-server
      register: sql_install
      failed_when: sql_install.rc != 0 and "is already installed" not in sql_install.stderr
    
    # Install SQL Server tools
    - name: Install SQL Server command-line tools
      apt:
        name:
          - mssql-tools
          - unixodbc-dev
        state: present
      environment:
        ACCEPT_EULA: "Y"
    
    # Add tools to PATH
    - name: Add SQL Server tools to PATH
      lineinfile:
        path: /etc/profile.d/mssql-tools.sh
        line: export PATH="$PATH:/opt/mssql-tools/bin"
        create: yes
        mode: '0644'
    
    # Configure SQL Server with SA password
    - name: Stop SQL Server before configuration
      systemd:
        name: mssql-server
        state: stopped
    
    - name: Configure SQL Server with SA password
      shell: |
        /opt/mssql/bin/mssql-conf setup
      environment:
        MSSQL_SA_PASSWORD: "{{ sa_password }}"
        MSSQL_PID: "Developer"
        ACCEPT_EULA: "Y"
    
    # Start SQL Server
    - name: Start SQL Server
      systemd:
        name: mssql-server
        state: started
        enabled: yes
    
    # Wait for server to be ready
    - name: Wait for SQL Server to be ready
      wait_for:
        port: 1433
        timeout: 60
    
    # Verify installation
    - name: Verify SQL Server version
      shell: |
        export PATH=$PATH:/opt/mssql-tools/bin
        /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "{{ sa_password }}" -Q "SELECT @@VERSION"
      register: sql_version_output
    
    - name: Display SQL Server version
      debug:
        var: sql_version_output.stdout_lines
