---
- name: Install WordPress and Connect to Database
  hosts: all
  become: yes
  vars:
    # Database variables using Ansible/Morpheus syntax
    db_user: "{{ morpheus['customOptions']['dbaasUsername'] }}"
    db_name: "{{ morpheus['customOptions']['dbName'] }}"
    db_password: "{{ morpheus['customOptions']['dbaasPassword'] }}"
    db_host: "{{ morpheus['database']['host'] }}"
    wordpress_version: "6.4.3"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apache2
          - php
          - php-mysql
          - php-curl
          - php-gd
          - php-mbstring
          - php-xml
          - php-zip
        state: present

    - name: Start Apache
      service:
        name: apache2
        state: started

    - name: Download WordPress
      get_url:
        url: "https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz"
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Create wp-config.php
      copy:
        content: |
          <?php
          define('DB_NAME', '{{ db_name }}');
          define('DB_USER', '{{ db_user }}');
          define('DB_PASSWORD', '{{ db_password }}');
          define('DB_HOST', '{{ db_host }}');
          define('DB_CHARSET', 'utf8');
          define('DB_COLLATE', '');

          {{ lookup('url', 'https://api.wordpress.org/secret-key/1.1/salt/') }}

          $table_prefix = 'wp_';
          define('WP_DEBUG', false);
          if (!defined('ABSPATH')) {
              define('ABSPATH', dirname(__FILE__) . '/');
          }
          require_once(ABSPATH . 'wp-settings.php');
        dest: /var/www/html/wordpress/wp-config.php

    - name: Set correct permissions
      file:
        path: /var/www/html/wordpress
        owner: www-data
        group: www-data
        recurse: yes

    - name: Clean up installation files
      file:
        path: /tmp/wordpress.tar.gz
        state: absent
