---
- hosts: all
  become: yes
  become_method: sudo
  become_user: root
  
  vars:
    # WordPress settings - customize these
    domain: example.com
    wp_user: admin
    wp_password: StrongPassword123
    wp_email: admin@example.com
    wp_title: "My WordPress Site"
    
    # Database settings - customize these
    db_name: wordpress
    db_user: wpuser
    db_password: DBPassword123

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    
    - name: Install required packages
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
          - php-curl
          - php-gd
          - php-mbstring
          - php-xml
          - php-xmlrpc
          - libapache2-mod-php
          - python3-pymysql
          - unzip
        state: present
    
    - name: Enable Apache modules
      command: a2enmod rewrite
      notify: Restart Apache
    
    - name: Create MySQL database
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
    
    - name: Create MySQL user
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        host: localhost
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
    
    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz
    
    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/
        remote_src: yes
    
    - name: Copy WordPress files to web root
      command: cp -a /var/www/wordpress/. /var/www/html/
      args:
        creates: /var/www/html/wp-config-sample.php
    
    # Generate secure keys for WordPress
    - name: Generate WordPress Security Keys
      set_fact:
        auth_key: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=64') }}"
        secure_auth_key: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=64') }}"
        logged_in_key: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=64') }}"
        nonce_key: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=64') }}"
        auth_salt: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=64') }}"
        secure_auth_salt: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=64') }}"
        logged_in_salt: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=64') }}"
        nonce_salt: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=64') }}"
    
    - name: Create wp-config.php
      copy:
        dest: /var/www/html/wp-config.php
        owner: www-data
        group: www-data
        content: |
          <?php
          /**
           * Basic WordPress config file
           */
          
          // Database settings
          define('DB_NAME', '{{ db_name }}');
          define('DB_USER', '{{ db_user }}');
          define('DB_PASSWORD', '{{ db_password }}');
          define('DB_HOST', 'localhost');
          define('DB_CHARSET', 'utf8');
          define('DB_COLLATE', '');
          
          // Authentication keys and salts
          define('AUTH_KEY',         '{{ auth_key }}');
          define('SECURE_AUTH_KEY',  '{{ secure_auth_key }}');
          define('LOGGED_IN_KEY',    '{{ logged_in_key }}');
          define('NONCE_KEY',        '{{ nonce_key }}');
          define('AUTH_SALT',        '{{ auth_salt }}');
          define('SECURE_AUTH_SALT', '{{ secure_auth_salt }}');
          define('LOGGED_IN_SALT',   '{{ logged_in_salt }}');
          define('NONCE_SALT',       '{{ nonce_salt }}');
          
          // Table prefix
          $table_prefix = 'wp_';
          
          // Debug mode
          define('WP_DEBUG', false);
          
          /* That's all, stop editing! */
          
          if (!defined('ABSPATH')) {
              define('ABSPATH', __DIR__ . '/');
          }
          
          require_once ABSPATH . 'wp-settings.php';
    
    - name: Set proper permissions
      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        recurse: yes
        
    - name: Set up Apache VirtualHost
      copy:
        dest: /etc/apache2/sites-available/wordpress.conf
        content: |
          <VirtualHost *:80>
              ServerAdmin webmaster@{{ domain }}
              ServerName {{ domain }}
              ServerAlias www.{{ domain }}
              DocumentRoot /var/www/html
              
              <Directory /var/www/html/>
                  Options FollowSymLinks
                  AllowOverride All
                  Require all granted
              </Directory>
              
              ErrorLog ${APACHE_LOG_DIR}/error.log
              CustomLog ${APACHE_LOG_DIR}/access.log combined
          </VirtualHost>
      notify: Restart Apache
        
    - name: Enable WordPress site
      command: a2ensite wordpress
      notify: Restart Apache
        
    - name: Disable default Apache site
      command: a2dissite 000-default
      notify: Restart Apache
    
    # Install WP-CLI for command-line management (optional)
    - name: Download WP-CLI
      get_url:
        url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        dest: /usr/local/bin/wp
        mode: '0755'
  
  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
